Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |vb|
     vb.memory = "2048"
     vb.cpus = 2
  end

  config.vm.define "puppetmaster" do |pm|
    pm.vm.box = "bento/centos-7.2"
    pm.vm.box_check_update = false
    pm.vm.network "private_network", ip: "192.168.33.10"
    pm.vm.hostname = "puppetmaster"
  end
  
  config.vm.define "puppetagent-centos" do |pac|
    pac.vm.box = "bento/centos-7.2"
    pac.vm.box_check_update = false
    pac.vm.network "private_network", ip: "192.168.33.11"
    pac.vm.hostname = "centos-agent"
  end

  config.vm.define "puppetagent-ubuntu" do |pau|
    pau.vm.box = "ubuntu/xenial64"
    pau.vm.box_check_update = false
    pau.vm.network "private_network", ip: "192.168.33.12"
    pau.vm.hostname = "ubuntu-agent"
  end
end
