vm_memory = 512
vm_cpus = 1

Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7.2"

  if Vagrant.has_plugin?("vagrant-vbguest") then
    config.vbguest.auto_update = false
  end
  
  config.vm.provider "virtualbox" do |vb|
     vb.memory = vm_memory
     vb.cpus = vm_cpus
  end
  
  config.vm.define "srv-1" do |config|
    config.vm.provision :shell, :inline => "ip addr | grep \"inet\" | awk '{print $2}'"
    config.vm.network "private_network", ip: "192.168.50.11", virtual__intnet: "true"
  end

  config.vm.define "srv-2" do |config|
    config.vm.provision :shell, :inline => "ip addr | grep \"inet\" | awk '{print $2}'"
    config.vm.network "private_network", ip: "192.168.50.12", virtual__intnet: "true"
  end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
